config/routes.rb
Rails.application.routes.draw do
  get 'packers/create'

  get 'welcome/index'

  resources :packers
  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/packers_controller.rb
class PackersController < ApplicationController
  def create
    # C:\opscode\chef-repo
    Dir.chdir('C:\\opscode\\chef-repo'){
      system('knife client create another_client -d')
    }

    # system('knife client create another_client -d')

    # system('packer build "C:\\website\\test_null.json"')
  end

  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/packers_helper.rb
module PackersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Packer</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/packers/create.html.erb
<h1>VM Created!</h1>

<%= link_to 'Back', packers_path %>

app/views/packers/index.html.erb
<!-- <h1>Hello, Rails!</h1> -->
<h1>Welcome Packer!</h1>


<%= form_for :packers, url: packers_path do |f| %>
  <p>
    <%= f.label :hostname %>:
    <%= f.text_field :hostname %>
    <%= f.submit "Build" %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<!-- <h1>Hello, Rails!</h1> -->
<h1>Welcome Packer!</h1>


<%= form_for :packers, url: packers_path do |f| %>
  <p>
    <%= f.label :hostname %>:
    <%= f.text_field :hostname %>
    <%= f.submit "Build" %>
  </p>
<% end %>